config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :friends
  get 'home/index'
  get '/test', to: 'test#index'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend
  include ActiveModel::Model

  attr_accessor :id
  attr_accessor :email
  validates_presence_of :email
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
  validates_presence_of :email, :word
  before_create { generate_token(:auth_token) }
  before_save { self.email = email.downcase.strip }

  has_and_belongs_to_many :friendships,
                          class_name: "User",
                          join_table:  :friendships,
                          foreign_key: :user_id,
                          association_foreign_key: :friend_user_id

  def make_friends(friend)
    friendships << friend
    friend.friendships << self
  end

  def unfriend(friend)
    friendships.destroy(friend)
    friend.friendships.destroy(self)
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private

  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end

  helper_method :current_user

  def authorise
    redirect_to new_user_path, alert: "Not authorised!" if current_user.nil?
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authorise

  def index
  end

  def new
    @friend = Friend.new
  end

  def create
    @friend = Friend.new(email: params[:friend][:email])

    if @friend.email.blank?
      flash.now.alert = 'Please enter email'
      render 'new'
      return
    end

    user = User.find_by_email(@friend.email)

    if user.nil?
      flash.now.alert = 'User does not exist'
      render 'new'
      return
    end

    if user == current_user
      flash.now.alert = "You can not friend yourself"
      render 'new'
      return
    end

    current_user.make_friends(user)
    redirect_to friends_path
  rescue ActiveRecord::RecordNotUnique
    flash.now.alert = "User #{@friend.email} is already your friend"
    render 'new'
  end

  def destroy
    friend = current_user.friendships.find(params[:id])
    current_user.friendships.destroy(friend)
    friend.friendships.destroy(current_user)

    redirect_to friends_path
  end

  private

  def friend_params
    params.require(:friend).permit(:email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email].downcase().strip
    user = User.find_by_email(email)

    if user && user.authenticate(params[:password])
      cookies.permanent[:auth_token] = user.auth_token
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render 'new'
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  layout "test"

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      cookies.permanent[:auth_token] = @user.auth_token
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to root_url, notice: "Profile updated"
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :word)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/score_helper.rb
module ScoreHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_friendship.html.erb
<tr>
  <td class="px-6 py-4 whitespace-no-wrap">
    <div class="flex items-center">
      <div class="flex-shrink-0 h-10 w-10">
        <%= image_tag "people/person_#{rand(5) + 1}.jpg", class: "h-10 w-10 rounded-full", alt: friendship.email %>
      </div>
      <div class="ml-4">
        <div class="text-sm leading-5 font-medium text-gray-900">
          <%= Faker::Name.name %>
        </div>
        <div class="text-sm leading-5 text-gray-500">
          <%= friendship.email %>
        </div>
      </div>
    </div>
  </td>
  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
    <%= Faker::Creature::Animal.name.capitalize %>
  </td>
  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
    <%= link_to 'Unfriend', friend_path(friendship),
                 method: :delete,
                 data: { confirm: 'Are you sure?' }, class: "text-green-700 hover:text-green-900" %>
  </td>
</tr>

app/views/friends/index.html.erb
<h1>Your friends</h1>

<p>
  <%= link_to 'Add a  friend', new_friend_path, class: "cursor-pointer bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
</p>


<% if current_user.friendships.empty? %>
  <p class='my-10'>You have no friends 😭😭😭.</p>
<% else %>

<div class="flex flex-col mt-10 mb-3">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                User
              </th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Favourite animal
              </th>
              <th class="px-6 py-3 bg-gray-50"></th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <%= render partial: "friendship", collection: current_user.friendships %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<p class="text-gray-500 text-xs">
  The images were generated by <a href="https://thispersondoesnotexist.com" class="underline" target="_blank">thispersondoesnotexist.com</a>.
</p>

<% end %>

app/views/friends/new.html.erb
<div class="flex justify-center">
  <div class="w-full max-w-xs">
    <h1 class="px-8">Add a new friend</h1>

    <%= form_with model: @friend, url: friends_path, local: true, class: "bg-white shadow-md rounded px-8 pt-6 pb-6 mb-4" do |f| %>

      <div class="mb-4">
        <%= f.label :email, nil, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_field :email, type: "email", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: 'Email' %>
      </div>

      <div class="flex justify-center">
        <%= f.submit 'Add Friend', class: "cursor-pointer bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>

    <% end %>

  </div>
</div>

app/views/home/index.html.erb
<% if current_user %>
  <h1>Welcome home, <%= current_user.email %>.</h1>
<% else %>
  <h1>Welcome!</h1>
<% end %>

<p>That's not what I'm talking about. But I'm hopeful because I think there's an awakening taking place in America. We have to do what we can, knowing it's hard and not swinging from a naive idealism to a bitter defeatism - but rather, accepting the fact that we're not going to solve every problem overnight, but we can still make a difference.</p>

<p>Our conscience cannot rest until we not only secure our borders, but give the 12 million undocumented immigrants in this country a chance to earn their citizenship by paying a fine and waiting in line behind all those who came here legally. These are not opinions to be debated; these are facts to be dealt with. And just as it devastates Palestinian families, the continuing humanitarian crisis in Gaza does not serve Israel's security; neither does the continuing lack of opportunity in the West Bank.</p>

<%= image_tag "whithousefly.jpg", alt: "President Obama receives a fly rod for his birthday", class: "my-5" %>

<p>Go into any inner city neighborhood, and folks will tell you that government alone can't teach our kids to learn - they know that parents have to teach, that children can't achieve unless we raise their expectations and turn off the television sets and eradicate the slander that says a black youth with a book is acting white. My faith teaches me that I can sit in church and pray all I want, but I won't be fulfilling God's will unless I go out and do the Lord's work.</p>

<p>We meet at a time of tension between the United States and Muslims around the world - tension rooted in historical forces that go beyond any current policy debate. Around the world, we can turn dialogue into Interfaith service, so bridges between peoples lead to action - whether it is combating malaria in Africa, or providing relief after a natural disaster. Americans are ready to join with citizens and governments; community organizations, religious leaders, and businesses in Muslim communities around the world to help our people pursue a better life.</p>

<p>Thank you, God Bless you, and God Bless the United States of America.</p>

<p class="text-gray-500 text-xs">
  This text was generated by <a href="https://obamaipsum.com/" class="underline" target="_blank">obamaipsum.com</a>.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="relative bg-gray-800">
      <div class="max-w-3xl mx-auto px-5">
        <div class="flex justify-between items-center py-4">
          <div>
            <a href="/" title='Home is where your cat is'>
              <img class="h-8 w-auto sm:h-10" src=<%= image_url 'logo.svg' %> alt="Quiz Home">
            </a>
          </div>
          <div class="flex items-center justify-end space-x-5">
            <% if current_user %>
              <%= link_to 'Friends', friends_path, class: "whitespace-no-wrap text-base leading-6 font-medium text-gray-300 hover:text-gray-500 focus:outline-none focus:text-gray-500" %>
              <%= link_to 'Profile', edit_user_path(current_user), class: "whitespace-no-wrap text-base leading-6 font-medium text-gray-300 hover:text-gray-500 focus:outline-none focus:text-gray-500" %>
              <span class="inline-flex rounded-md shadow-sm">
                <%= link_to "Logout", session_path("wow"), method: :delete, class: "whitespace-no-wrap inline-flex items-center justify-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:border-green-900 focus:shadow-outline-green active:bg-green-700 transition ease-in-out duration-150" %>
              </span>
            <% else %>
              <%= link_to "Sign In", new_session_path, class: "whitespace-no-wrap text-base leading-6 font-medium text-gray-300 hover:text-gray-500 focus:outline-none focus:text-gray-500" %>
              <span class="inline-flex rounded-md shadow-sm">
                <%= link_to "Sign Up", new_user_path, class: "whitespace-no-wrap inline-flex items-center justify-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:border-green-900 focus:shadow-outline-green active:bg-green-700 transition ease-in-out duration-150" %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="max-w-3xl mx-auto px-5 pt-5">
      <% if flash[:alert] %>
        <div class="text-center mb-5">
          <div class="p-2 bg-red-700 items-center text-white leading-none rounded-full flex inline-flex" role="alert">
            <span class="flex rounded-full bg-red-500 uppercase px-2 py-1 text-xs font-bold mr-3">Error</span>
            <span class="font-semibold mr-2 text-left flex-auto"><%= alert %></span>
          </div>
        </div>
      <% end %>

      <% if flash[:notice] %>
        <div class="text-center mb-5">
          <div class="p-2 bg-green-800 items-center text-white leading-none rounded-full flex inline-flex" role="alert">
            <span class="flex rounded-full bg-green-500 uppercase px-2 py-1 text-xs font-bold mr-3">Success</span>
            <span class="font-semibold mr-2 text-left flex-auto"><%= flash.notice %></span>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/test.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tests</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'mocha', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'test/main' %>
  </head>

  <body>
    <div id="mocha"></div>
    <div class="TestFixture"></div>

    <%= yield %>

    <%= javascript_pack_tag 'test/setup', type: 'module' %>
    <%= javascript_pack_tag 'run_tests', type: 'module' %>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="bg-red-100 border-l-4 border-red-500 text-red-700 px-8 py-5 mb-4" role="alert">
    <h2>Form is invalid</h2>

    <ul class="list-disc">
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    <ul>
  </div>
<% end %>

<%= form_with model: @user, local: true, class: "bg-white shadow-md rounded px-8 pt-6 pb-6 mb-4" do |f| %>
  <div class="mb-4">
    <%= f.label :email, nil, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.text_field :email, type: "email", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: 'Email' %>
  </div>

  <div class="mb-4">
    <%= f.label :password, nil, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.password_field :password, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: '*************' %>
  </div>

  <div class="mb-4">
    <%= f.label :password_confirmation, nil, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.password_field :password_confirmation, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: '*************' %>
  </div>

  <div class="mb-3">
    <%= f.label :word, nil, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.text_field :word, class: "Quiz-wordInput shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: 'Your word' %>
  </div>

  <div class="flex justify-center mb-4">
    <span class="Quiz-wordScore text-lg rounded-full text-green-700 border-2 border-green-600 uppercase px-2 py-1 font-bold">Success</span>
  </div>

  <div class="flex justify-center">
    <%= f.submit (@user.id? ? 'Save' : 'Sign Up'), class: "cursor-pointer bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

<%= javascript_pack_tag 'word_counter/init.js', 'data-turbolinks-track': 'reload' %>

app/views/users/edit.html.erb
<div class="flex justify-center">
  <div class="w-full max-w-sm">
    <h1 class="px-8">Edit profile</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="flex justify-center">
  <div class="w-full max-w-xs">
    <h1 class="px-8">Sign Up</h1>

    <%= render 'form' %>

    <div class="text-center">
      Existing user?
      <%= link_to "Log In", new_session_path, class: 'font-bold text-green-700 hover:text-green-500' %>
    </div>

  </div>
</div>